@startuml
actor Customer as c
participant Store as u
participant Customer as a
participant Address as ad
participant Order as o

c -> u : create account
c -> a : new Customer()
c -> a : addToArrayList()
c -> ad : new Address()
ad --> c : addressAdded

a --> c : registrationSuccess

c -> u : login (Customer)
u -> a : check customer
a -> u : confirmed customer
u --> c : loginConfirmed


alt Failed login
    u --> c : loginFailed
end

c -> o : viewOrderHistory
o --> c : orderHistory

c -> u : logout()
u -> c : logoutSuccess
@enduml