@startuml
actor Customer as c
participant Inventory as i
participant Product as p
participant Cart as o

' Dodawanie do koszyka

c -> i : getProducts()
i --> c : ArrayList<Product>

c -> o : addProduct(product: Product, int quantity)
o -> p : updateProductQuantity(Products product, int delta)
p --> o : updated

c -> o : getTotalPrice()
o --> c : totalAmount

c -> o : placeOrder()

@enduml
