@startuml
actor Customer as c
participant Address as cust

c -> cust : new Address()
cust --> c : Address updated confirmation


c -> cust : setCountry("Poland")
c -> cust : setCity("Warsaw")
c -> cust : setStreet("Marszalkowska")
c -> cust : setNumberOfStreet("1")
c -> cust : setPostalNumber("1")

cust --> c : Address updated confirmation


@enduml