@startuml
actor Customer as c
participant Address as a
participant Cart as o
participant Inventory as i
participant Product as p



c -> a : new Address()

c -> i : getProducts()
i --> c : ArrayList<Product>

c -> o : addProduct()
o -> p : setProductQuantity()


c -> o : getTotalPrice()
o --> c : totalPrice

c -> o : placeOrder()
    o -> i : removeProduct()
    i --> o : updateProductQuantity
    o --> c : Order confirmation
    o --> c : Return Invoice


@enduml
