@startuml

class Sklep {
    -nazwa: String
    -lista_produktow: List<Produkt>
    -lista_uzytkownikow: List<Uzytkownik>
    -lista_zamowien: List<Zamowienie>
    #dodajProduktDoListy(Produkt produkt): void
    #usunProduktZListy(String id): void
    #dodajUzytkownikaDoBazy(int id)
    #usunUzytkownikaZBazy(int id)
    #dodajZamowienieDoListy(int id)
    +wyswietlProdukty(): void
    +wyswietlZamowienia(): void
}

class Produkt {
    -nazwa: String
    -cena: float
    -id: int
    -ilosc: int
    +aktualizujIlosc(int nowaIlosc): void
    +aktualizujCene(float nowaCena): void
    +wyswietlSzczegoly(): void
}

class Kategoria {
    -nazwa: String
    -opis: String
    +dodajProdukt(Produkt produkt): void
    +usunProdukt(Produkt produkt): void
    +wyswietlKategorie(): void
    +wyswietlOpis(): void
}

class Producent {
    -nazwa: String
    -kontakt: String
    +aktualizujKontakt(String nowyKontakt): void
    +wyswietlSzczegoly(): void
}

class Uzytkownik {
    -id: int
    -imie: String
    -nazwisko: String
    -email: String
    -nr_tel: String
    +aktualizujDane(String imie, String nazwisko, String email, String nr_tel): void
    +wyswietlDane(): void
}

class Admin {
    +dodajProdukt(Produkt produkt): void
    +usunProdukt(String id): void
}

class Klient {
    -historia_zakupow: List<Zamowienie>
    -NIP: String
    +zlozZamowienie(Zamowienie zamowienie): void
    +wyswietlHistorieZakupow(): void
    +dodajAdres(Adres adres): void
    +usunAdres(Adres adres): void
}

class Adres {
    -miejscowosc: String
    -ulica: String
    -kod_pocztowy: String
    -kraj: String
    -nr_domu_mieszkania: String
    +aktualizujAdres(String miejscowosc, String ulica, String kodPocztowy, String kraj, String nrDomuMieszkania): void
    +wyswietlAdres(): void
}

class Zamowienie {
    -id: int
    -lista_produktow: List<Produkt>
    -data_zamowienia: Date
    -suma: float
    -id_klienta: String
    -sposob_platnosci: String
    +dodajProdukt(Produkt produkt, int ilosc): void
    +usunProdukt(Produkt produkt): void
    +obliczSume(): float
    +wyswietlSzczegoly(): void
}

class Faktura {
    -klient: Klient
    -nr_faktury: String
    -produkty: List<Produkt>
    -suma: float
    -data: Date
    +generujFakture(): void
    +wyswietlSzczegoly(): void
}

class Koszyk {
    -produkty: List<Produkt>
    -ilosc_produktu: Map<Produkt, int>
    +dodajDoKoszyka(Produkt produkt, int ilosc): void
    +usunZKoszyka(Produkt produkt): void
    +wyswietlKoszyk(): void
    +obliczSumeKoszyka(): float
}

Sklep "1" *-- "*" Produkt
Sklep "1" *-- "*" Uzytkownik
Sklep "1" *-- "*" Zamowienie
Produkt "1" o-- "1" Kategoria
Produkt "1" o-- "1" Producent
Uzytkownik <|-- Admin
Uzytkownik <|-- Klient
Klient "1" *-- "*" Zamowienie
Klient "1" *-- "*" Adres
Zamowienie "1" *-- "*" Produkt
Klient "1" *-- "1" Faktura
Faktura "1" *-- "*" Produkt
Koszyk "1" *-- "*" Produkt
Zamowienie "1" *-- "1" Faktura
@enduml